use strict;
use warnings;

use Test::More;

# Generated by:
# $ find lib -name \*.pm | sort | sed -es,^lib/,use_ok\(\', -es,/,::,g -es,\.pm,\'\)\;,

use_ok('microservice');
use_ok('Myriad::Bootstrap');
use_ok('Myriad::Config');
use_ok('Myriad::Exception');
use_ok('Myriad::Notifier');
use_ok('Myriad::Plugin');
use_ok('Myriad');
use_ok('Myriad::Redis::Pending');
use_ok('Myriad::Registry');
use_ok('Myriad::RPC::Implementation::Redis');
use_ok('Myriad::RPC');
use_ok('Myriad::Service::Attributes');
use_ok('Myriad::Service');
use_ok('Myriad::Storage::Perl');
use_ok('Myriad::Storage');
use_ok('Myriad::Storage::Redis');
use_ok('Myriad::Subscription');
use_ok('Myriad::Transport::AMQP');
use_ok('Myriad::Transport::HTTP');
use_ok('Myriad::Transport::PostgreSQL');
use_ok('Myriad::Transport::Redis');

done_testing;
