transport: value_from_file

services:
    fake.name:
        config:
            key: value from file
        instance:
            demo:
                config:
                    key: instance value from file

